#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 29 10:36:06 CEST 2025
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim instr_memory_tb_behav -key {Behavioral:sim_1:Functional:instr_memory_tb} -tclbatch instr_memory_tb.tcl -log simulate.log"
xsim instr_memory_tb_behav -key {Behavioral:sim_1:Functional:instr_memory_tb} -tclbatch instr_memory_tb.tcl -log simulate.log

